### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by siyuan126** [mnjune/pwp-capstones#1]
**Overall Score: 11/20**
Overall good work, here is the breakdown. 

**Criteria 1: Valid Python Code**
Score Level: 1 (do not meet expectations)
Comment(s): Code included runs with errors. There is a Type Error in function get_average_sentence_length, this error shows up because of sum(word_total), sum is a built-in function that sums up the numbers in the list. Here word_total is an integer. Please use this info for debug. In function prepare_text, there is no need to use sort() method, it will sort a list with ascending, descending or user defined order, here we just want the word in the same order they shows up in the sentence. 

**Criteria 2: Implementation of Project Requirements**
Score Level: 2 (approaches expectations)
Comment(s): Code produces the suite of functions and classes required of it, since several cells are not run, it is hard for me to tell if these functions and classes are called  in an appropriate order. 

**Criteria 3: Software Architecture**
Score Level: 3 (meets expectations)
Comment(s): Code is separated into distinct classes and functions each which are invoked for their own purposes.

**Criteria 4: Uses Python Language Features**
Score Level: 3 (meets expectations)
Comment(s): Code uses language features appropriately. If a task can be solved with a Python language feature, it is. Here are some minor issues. Please use triple quotes for multi-line strings. In function prepare_text, replace is used four times in a row, I would recommend to reduce the repetitiveness of same code. 

**Criteria 5: Produces Accurate Output**
Score Level: 2 (Approaches expectations)
Comment(s): Code output is not indicated.

**Comment by mnjune** [comment]
> **Overall Score: 11/20**
> Overall good work, here is the breakdown.
> 
> **Criteria 1: Valid Python Code**
> Score Level: 1 (do not meet expectations)
> Comment(s): Code included runs with errors. There is a Type Error in function get_average_sentence_length, this error shows up because of sum(word_total), sum is a built-in function that sums up the numbers in the list. Here word_total is an integer. Please use this info for debug. In function prepare_text, there is no need to use sort() method, it will sort a list with ascending, descending or user defined order, here we just want the word in the same order they shows up in the sentence.
> 
> **Criteria 2: Implementation of Project Requirements**
> Score Level: 2 (approaches expectations)
> Comment(s): Code produces the suite of functions and classes required of it, since several cells are not run, it is hard for me to tell if these functions and classes are called in an appropriate order.
> 
> **Criteria 3: Software Architecture**
> Score Level: 3 (meets expectations)
> Comment(s): Code is separated into distinct classes and functions each which are invoked for their own purposes.
> 
> **Criteria 4: Uses Python Language Features**
> Score Level: 3 (meets expectations)
> Comment(s): Code uses language features appropriately. If a task can be solved with a Python language feature, it is. Here are some minor issues. Please use triple quotes for multi-line strings. In function prepare_text, replace is used four times in a row, I would recommend to reduce the repetitiveness of same code.
> 
> **Criteria 5: Produces Accurate Output**
> Score Level: 2 (Approaches expectations)
> Comment(s): Code output is not indicated.

**Resubmit - Thank you so much for this review @siyuan126  and the debugging advice. I really appreciate it. I have debugged and resubmitted the project here for your review. Thanks again!**
